#Snakemake configuration file chimp

#Specify paths to data files

#Paths must end with forward slash

#project directory
dir_proj: /project2/gilad/briana/comparitive_threeprime/chimp/

#ref genome directory
dir_genome: /project2/gilad/briana/genome_anotation_data/comp_genomes/chimp/


#directory with aditional scripts:
scripts: /project2/gilad/briana/comparitive_threeprime/code/


# Make sure to also update path for log files in cluster.json
dir_log: log/


#add species label  
spe: chimp
spe_gen: panTro5.fa  
spe_lengths: /project2/gilad/briana/genome_anotation_data/comp_genomes/chimp/panTro5.chrom.sizes
