---
title: "Initial Read Stats"
author: "Briana Mittleman"
date: "8/20/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

I have processed the samples with the initial snakefile and now I want to look at read numbers and mapped read numbers.  
```{r}
library(tidyverse)
library(cowplot)
library(workflowr)
``` 



```{r}
map_stat=read.table("../data/map.stats.csv", header=T, sep=",")
```

Plot reads and maps:  

```{r}
ggplot(map_stat, aes(x=Line, y=Reads, fill=Species))+ geom_bar(stat="identity", position="dodge") +labs(y="Reads", title="Reads by line and fraction") + facet_grid(~Fraction)


ggplot(map_stat, aes(x=Line, y=Mapped, fill=Species))+ geom_bar(stat="identity", position="dodge") +labs(y="Mapped Reads", title="Mapped reads by line and fraction")  + facet_grid(~ Fraction)



ggplot(map_stat, aes(x=Line, y=X.Mapped, fill=Species))+ geom_bar(stat="identity", position="dodge") +labs(y="Mapped %", title="% Mapped reads by line and fraction")  + facet_grid(~ Fraction)
```

